import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";
import NewsFeed from "@/app/components/NewsFeed";
import SubscribeForm from "@/app/components/SubscribeForm";
import Riwayat from "@/app/components/Riwayat";

import cast from "@/assets/actress/cast.png";
import jiwon from "@/assets/actress/kim-ji-won.png";
import photo from "@/assets/actress/1.jpg";
import parasite from "@/assets/movies/parasite.jpg";
import snowpiercer from "@/assets/movies/snowpiercer.jpg";
import memory from "@/assets/movies/memory.jpg";
import host from "@/assets/movies/host.jpg";
import lady from "@/assets/movies/lady.jpg";
import taxi from "@/assets/movies/taxi.jpg";
import thirst from "@/assets/movies/thirst.jpg";

export default function Detail() {
  const roleData = [
    {
      title: "parasite",
      image: parasite,
    },
    {
      title: "snowpiercer",
      image: snowpiercer,
    },
    {
      title: "memories of murder",
      image: memory,
    },
    {
      title: "the host",
      image: host,
    },
    {
      title: "sympathy for lady vengeance",
      image: lady,
    },
    {
      title: "a taxi driver",
      image: taxi,
    },
    {
      title: "thirst",
      image: thirst,
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="flex h-12 md:h-20 bg-black w-full max-w-screen-xl"></div>
      <div className="relative md:relative w-full flex flex-col justify-center md:h-[480px] mx-auto h-[420px] xs:items-end xs:justify-end md:items-start md:justify-center text-white ">
        <div className="absolute z-10 top-0 h-36 w-full bg-gradient-to-t from-transparent to-black"></div>
        <div className="absolute z-10 bottom-0 h-40 w-full bg-gradient-to-b from-transparent to-[#0a1016]"></div>
        <div className="absolute w-full h-full">
          <div className="w-full h-full">
            <div
              className="bg-mask flex h-full md:block md:w-full md:h-full relative transition duration-300 ease-out "
              style={{
                background:
                  "linear-gradient(rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 15%)",
              }}
            >
              <Image src={cast} alt="" className="object-cover h-full w-full" />
            </div>
          </div>
        </div>
        <div className="md:relative md:mt-12 md:pb-20 bottom-0 z-10 h-full flex flex-col rounded justify-center  items-center text-center  xs:my-[12px] md:my-[48px] px-[12px] md:px-[30px] mx-auto md:w-full  xs:items-center xs:text-center xs:justify-center md:items-start md:text-left md:justify-center">
          <div className="flex-row md:flex px-4 md:px-6 md:space-x-7 w-full justify-between">
            <div className="flex-col mx-auto2 w-full md:w-2/3 justify-center ">
              <div className="flex flex-col space-y-0 items-center2">
                <div className="flex justify-center md:justify-start">
                  <div>
                    <div className="flex items-center text-black ">
                      <div className="">
                        <span className="text-3xl md:text-4xl font-bold">
                          Kim Ji-won
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                <section className="py-2 bg-transparent md:text-sm">
                  <div className="grid-container px-0 lg:px-0">
                    <nav aria-label="breadcrumbs">
                      <div className="relative w-full">
                        <ul className="scrollbar-fix flex flex-row flex-nowrap justify-start overflow-x-scroll no-scrollbar">
                        <li className='before:inline before:px-0 before:text-sm before:content-[""] text-black text-[11px] font-medium capitalize leading-3 tracking-[2px] opacity-100'>
                            <span className="whitespace-nowrap text-sm font-semibold text-black text-[11px] capitalize leading-3 tracking-[2px] opacity-100">
                              Actress
                            </span>
                          </li>

                          <li className='before:inline before:px-1 before:text-sm before:content-["・"] text-black text-[11px] font-medium capitalize leading-3 tracking-[2px] opacity-100'>
                            <span className="whitespace-nowrap text-sm font-semibold text-black text-[11px] capitalize leading-3 tracking-[2px] opacity-100">
                              Producer
                            </span>
                          </li>

                          <li className='before:inline before:px-1 before:text-sm before:content-["・"] text-black text-[11px] font-medium capitalize leading-3 tracking-[2px] opacity-100'>
                            <span className="whitespace-nowrap text-sm font-semibold text-black text-[11px] capitalize leading-3 tracking-[2px] opacity-100">
                              Director
                            </span>
                          </li>
                        </ul>
                      </div>
                    </nav>
                  </div>
                </section>
              </div>
            </div>
          </div>

          <div className="flex gap-3"></div>
        </div>
      </div>
      <div className="flex h-6 md:h-8 bg-[#0a1016] w-full max-w-screen-xl"></div>

      <div className="flex-col min-h-screen relative bg-[#0a1016]  px-4 md:px-8 md:pt-3 pb-10">
        <div className="py-5">
          <div className="flex flex-col md:flex-row md:space-x-4">
            <div className="w-full md:w-1/3">
              <div className="flex flex-col md:no-flex relative overflow-hidden2 md:bg-white md:shadow md:rounded">
                <div className="hidden md:flex justify-center mx-auto w-36 md:w-full">
                  <Image
                    src={jiwon}
                    alt=""
                    className="relative rounded shadow w-36 md:w-full"
                  />
                </div>
                <div className="py-3 md:hidden text-center">
                  <span className="text-3xl font-semibold text-white">
                    Kim Ji-won
                  </span>
                </div>
                <div className="md:hidden flex justify-center space-x-3 px-10 mb-4">
                  <div className="border hover:bg-[#1877f2] w-10 h-10 fill-[#1877f2] hover:fill-white border-[#5aa3ed] rounded-full flex items-center justify-center shadow-xl hover:shadow-blue-500/50 cursor-pointer">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                    >
                      <path d="M13.397 20.997v-8.196h2.765l.411-3.209h-3.176V7.548c0-.926.258-1.56 1.587-1.56h1.684V3.127A22.336 22.336 0 0 0 14.201 3c-2.444 0-4.122 1.492-4.122 4.231v2.355H7.332v3.209h2.753v8.202h3.312z"></path>
                    </svg>
                  </div>

                  <div className="border hover:bg-[#1d9bf0] w-10 h-10 fill-[#1d9bf0] hover:fill-white border-[#1d9bf0] rounded-full flex items-center justify-center shadow-xl hover:shadow-sky-500/50 cursor-pointer">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                    >
                      <path d="M19.633 7.997c.013.175.013.349.013.523 0 5.325-4.053 11.461-11.46 11.461-2.282 0-4.402-.661-6.186-1.809.324.037.636.05.973.05a8.07 8.07 0 0 0 5.001-1.721 4.036 4.036 0 0 1-3.767-2.793c.249.037.499.062.761.062.361 0 .724-.05 1.061-.137a4.027 4.027 0 0 1-3.23-3.953v-.05c.537.299 1.16.486 1.82.511a4.022 4.022 0 0 1-1.796-3.354c0-.748.199-1.434.548-2.032a11.457 11.457 0 0 0 8.306 4.215c-.062-.3-.1-.611-.1-.923a4.026 4.026 0 0 1 4.028-4.028c1.16 0 2.207.486 2.943 1.272a7.957 7.957 0 0 0 2.556-.973 4.02 4.02 0 0 1-1.771 2.22 8.073 8.073 0 0 0 2.319-.624 8.645 8.645 0 0 1-2.019 2.083z"></path>
                    </svg>
                  </div>

                  <div className="border hover:bg-[#bc2a8d] w-10 h-10 fill-[#bc2a8d] hover:fill-white border-[#bc2a8d] rounded-full flex items-center justify-center shadow-xl hover:shadow-pink-500/50 cursor-pointer">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                    >
                      <path d="M11.999 7.377a4.623 4.623 0 1 0 0 9.248 4.623 4.623 0 0 0 0-9.248zm0 7.627a3.004 3.004 0 1 1 0-6.008 3.004 3.004 0 0 1 0 6.008z"></path>
                      <circle cx="16.806" cy="7.207" r="1.078"></circle>
                      <path d="M20.533 6.111A4.605 4.605 0 0 0 17.9 3.479a6.606 6.606 0 0 0-2.186-.42c-.963-.042-1.268-.054-3.71-.054s-2.755 0-3.71.054a6.554 6.554 0 0 0-2.184.42 4.6 4.6 0 0 0-2.633 2.632 6.585 6.585 0 0 0-.419 2.186c-.043.962-.056 1.267-.056 3.71 0 2.442 0 2.753.056 3.71.015.748.156 1.486.419 2.187a4.61 4.61 0 0 0 2.634 2.632 6.584 6.584 0 0 0 2.185.45c.963.042 1.268.055 3.71.055s2.755 0 3.71-.055a6.615 6.615 0 0 0 2.186-.419 4.613 4.613 0 0 0 2.633-2.633c.263-.7.404-1.438.419-2.186.043-.962.056-1.267.056-3.71s0-2.753-.056-3.71a6.581 6.581 0 0 0-.421-2.217zm-1.218 9.532a5.043 5.043 0 0 1-.311 1.688 2.987 2.987 0 0 1-1.712 1.711 4.985 4.985 0 0 1-1.67.311c-.95.044-1.218.055-3.654.055-2.438 0-2.687 0-3.655-.055a4.96 4.96 0 0 1-1.669-.311 2.985 2.985 0 0 1-1.719-1.711 5.08 5.08 0 0 1-.311-1.669c-.043-.95-.053-1.218-.053-3.654 0-2.437 0-2.686.053-3.655a5.038 5.038 0 0 1 .311-1.687c.305-.789.93-1.41 1.719-1.712a5.01 5.01 0 0 1 1.669-.311c.951-.043 1.218-.055 3.655-.055s2.687 0 3.654.055a4.96 4.96 0 0 1 1.67.311 2.991 2.991 0 0 1 1.712 1.712 5.08 5.08 0 0 1 .311 1.669c.043.951.054 1.218.054 3.655 0 2.436 0 2.698-.043 3.654h-.011z"></path>
                    </svg>
                  </div>
                </div>
              </div>
              <div className="flex-col py-2 md:py-4 text-white">
                <span className="text-xl font-semibold">Tentang</span>
                <div className="flex-col space-y-2 md:space-y-3 pt-2 md:pt-4">
                  <div className="flex-col">
                    <div className="">
                      <span className="font-semibold">Peran</span>
                    </div>
                    <div>
                      <span className="text-sm">Riwayat Perfilman</span>
                    </div>
                  </div>
                  <div className="flex-col">
                    <div>
                      <span className="font-semibold">Jenis kelamin</span>
                    </div>
                    <div>
                      <span className="text-sm">Wanita</span>
                    </div>
                  </div>
                  <div className="flex-col">
                    <div>
                      <span className="font-semibold">Kelahiran</span>
                    </div>
                    <div>
                      <span className="text-sm">1967-01-17 (55 years old)</span>
                    </div>
                  </div>

                  <div className="flex-col">
                    <div>
                      <span className="font-semibold">Lokasi Kelahiran</span>
                    </div>
                    <div>
                      <span className="text-sm">
                        Gimhae, South Gyeongsang, South Korea
                      </span>
                    </div>
                  </div>
                  <div className="flex-col">
                    <div>
                      <span className="font-semibold">
                        Juga Dikenal Sebagai
                      </span>
                    </div>
                    <div>
                      <span className="text-sm">송강호 Song Kang Ho</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="w-full md:w-2/3 md:pl-3">
              <div className="text-white">
                <div className="hidden md:flex justify-between">
                  <span className="text-3xl font-bold">Kim Ji-won</span>
                  <div className="flex justify-end space-x-2  mb-0">
                  <div className="border hover:bg-[#1877f2] w-8 h-8 fill-[#1877f2] hover:fill-white border-[#5aa3ed] rounded-full flex items-center justify-center shadow-xl hover:shadow-blue-500/50 cursor-pointer">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                    >
                      <path d="M13.397 20.997v-8.196h2.765l.411-3.209h-3.176V7.548c0-.926.258-1.56 1.587-1.56h1.684V3.127A22.336 22.336 0 0 0 14.201 3c-2.444 0-4.122 1.492-4.122 4.231v2.355H7.332v3.209h2.753v8.202h3.312z"></path>
                    </svg>
                  </div>

                  <div className="border hover:bg-[#1d9bf0] w-8 h-8 fill-[#1d9bf0] hover:fill-white border-[#1d9bf0] rounded-full flex items-center justify-center shadow-xl hover:shadow-sky-500/50 cursor-pointer">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                    >
                      <path d="M19.633 7.997c.013.175.013.349.013.523 0 5.325-4.053 11.461-11.46 11.461-2.282 0-4.402-.661-6.186-1.809.324.037.636.05.973.05a8.07 8.07 0 0 0 5.001-1.721 4.036 4.036 0 0 1-3.767-2.793c.249.037.499.062.761.062.361 0 .724-.05 1.061-.137a4.027 4.027 0 0 1-3.23-3.953v-.05c.537.299 1.16.486 1.82.511a4.022 4.022 0 0 1-1.796-3.354c0-.748.199-1.434.548-2.032a11.457 11.457 0 0 0 8.306 4.215c-.062-.3-.1-.611-.1-.923a4.026 4.026 0 0 1 4.028-4.028c1.16 0 2.207.486 2.943 1.272a7.957 7.957 0 0 0 2.556-.973 4.02 4.02 0 0 1-1.771 2.22 8.073 8.073 0 0 0 2.319-.624 8.645 8.645 0 0 1-2.019 2.083z"></path>
                    </svg>
                  </div>

                  <div className="border hover:bg-[#bc2a8d] w-8 h-8 fill-[#bc2a8d] hover:fill-white border-[#bc2a8d] rounded-full flex items-center justify-center shadow-xl hover:shadow-pink-500/50 cursor-pointer">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                    >
                      <path d="M11.999 7.377a4.623 4.623 0 1 0 0 9.248 4.623 4.623 0 0 0 0-9.248zm0 7.627a3.004 3.004 0 1 1 0-6.008 3.004 3.004 0 0 1 0 6.008z"></path>
                      <circle cx="16.806" cy="7.207" r="1.078"></circle>
                      <path d="M20.533 6.111A4.605 4.605 0 0 0 17.9 3.479a6.606 6.606 0 0 0-2.186-.42c-.963-.042-1.268-.054-3.71-.054s-2.755 0-3.71.054a6.554 6.554 0 0 0-2.184.42 4.6 4.6 0 0 0-2.633 2.632 6.585 6.585 0 0 0-.419 2.186c-.043.962-.056 1.267-.056 3.71 0 2.442 0 2.753.056 3.71.015.748.156 1.486.419 2.187a4.61 4.61 0 0 0 2.634 2.632 6.584 6.584 0 0 0 2.185.45c.963.042 1.268.055 3.71.055s2.755 0 3.71-.055a6.615 6.615 0 0 0 2.186-.419 4.613 4.613 0 0 0 2.633-2.633c.263-.7.404-1.438.419-2.186.043-.962.056-1.267.056-3.71s0-2.753-.056-3.71a6.581 6.581 0 0 0-.421-2.217zm-1.218 9.532a5.043 5.043 0 0 1-.311 1.688 2.987 2.987 0 0 1-1.712 1.711 4.985 4.985 0 0 1-1.67.311c-.95.044-1.218.055-3.654.055-2.438 0-2.687 0-3.655-.055a4.96 4.96 0 0 1-1.669-.311 2.985 2.985 0 0 1-1.719-1.711 5.08 5.08 0 0 1-.311-1.669c-.043-.95-.053-1.218-.053-3.654 0-2.437 0-2.686.053-3.655a5.038 5.038 0 0 1 .311-1.687c.305-.789.93-1.41 1.719-1.712a5.01 5.01 0 0 1 1.669-.311c.951-.043 1.218-.055 3.655-.055s2.687 0 3.654.055a4.96 4.96 0 0 1 1.67.311 2.991 2.991 0 0 1 1.712 1.712 5.08 5.08 0 0 1 .311 1.669c.043.951.054 1.218.054 3.655 0 2.436 0 2.698-.043 3.654h-.011z"></path>
                    </svg>
                  </div>
                </div>
                </div>
                <div className="pt-6">
                  <div className="text-lg font-semibold">Biografi</div>
                  <div className="py-2 text-md">
                    <span>
                      Kim Ji-won (Hangul: 김지원; Hanja: 金智媛; born October
                      19, 1992) is a South Korean actress. She gained attention
                      through her roles in television series To the Beautiful
                      You (2012), The Heirs (2013), Descendants of the Sun
                      (2016), and Fight For My Way (2017).
                    </span>
                  </div>
                </div>
                <div className="py-3">
                  <div>
                    <span className="text-lg font-semibold">Peran</span>
                  </div>
                  <div className="py-2 overflow-auto custom-scrollbar">
                    <div className="inline-flex space-x-3">
                      {roleData.map((role, id) => (
                        <div
                          className="flex-col justify-center w-32 space-y-2"
                          key={id}
                        >
                          <div className="relative  overflow-hidden bg-white shadow flex rounded">
                            <Image
                              src={role.image}
                              alt=""
                              className="relative w-full"
                            />
                          </div>
                          <div className="text-center text-sm capitalize">
                            <span>{role.title}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                <div className="">
                  <div>
                    <div>
                      <span className="text-xl font-semibold">
                        Riwayat Perfilman
                      </span>
                    </div>
                    <div>
                      <Riwayat />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <SubscribeForm />
      <Footer />
    </>
  );
}
