import Image from "next/image";
import Head from "next/head";

import Footer from "./components/Footer";
import Header from "./components/Header";
import GoTop from "./components/GoTop";
import SubscribeForm from "./components/SubscribeForm";
import Chat from "./components/Chat";
import Hero from "./components/Hero";
import CookieConsent from "./components/CookieConsent";
import TrendingHome from "./components/TrendingHome";
import NewRelease from "./components/NewRelease";
import ActressList from "./components/ActressList";

export default function Home() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />
    <GoTop />
    <Hero />
    <Chat />

    <TrendingHome />
    <NewRelease />
    <ActressList />
    <SubscribeForm />
    <CookieConsent />
    <Footer />
    </>
  );
}
