import Image from "next/image";
import Head from "next/head";

import Footer from "./components/Footer";
import Header from "./components/Header";
import GoTop from "./components/GoTop";
import SubscribeForm from "./components/SubscribeForm";
import Chat from "./components/Chat";
import Hero from "./components/Hero";
import CookieConsent from "./components/CookieConsent";
import TrendingHome from "./components/TrendingHome";
import NewRelease from "./components/NewRelease";
import ActressList from "./components/ActressList";
import MusicList from "./components/MusicList";
import ProductShop from "./components/ProductShop";
import AdsModal from "./components/AdsModal";
import LatestNews from "./components/LatestNews";

export default function Home() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />
    <GoTop />
    <Hero />
    <Chat />

    <LatestNews />
    <TrendingHome />
    <NewRelease />
    <ActressList />
    <MusicList />
    
    <ProductShop />


    <SubscribeForm />
    <CookieConsent />
    <AdsModal />
    <Footer />
    </>
  );
}
