import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";
import NewsFeed from "../components/NewsFeed";
import FilterMovie from "../components/FilterMovie";
import SubscribeForm from "../components/SubscribeForm";
import PaginateMovie from "../components/PaginateMovie";

import movie1 from "@/assets/movies/movie1.jpg";
import movie2 from "@/assets/movies/movie2.jpg";
import movie3 from "@/assets/movies/movie3.jpg";
import movie4 from "@/assets/movies/movie4.jpg";
import movie5 from "@/assets/movies/movie5.jpg";
import movie6 from "@/assets/movies/movie6.jpg";
import movie7 from "@/assets/movies/movie7.jpg";
import movie8 from "@/assets/movies/movie8.jpg";
import movie9 from "@/assets/movies/movie9.jpg";
import movie10 from "@/assets/movies/movie10.jpg";
import movie11 from "@/assets/movies/movie11.jpg";
import movie12 from "@/assets/movies/movie12.jpg";
import movie13 from "@/assets/movies/movie13.jpg";
import movie14 from "@/assets/movies/movie14.jpg";
import movie15 from "@/assets/movies/movie15.jpg";
import movie16 from "@/assets/movies/movie16.jpg";
import movie17 from "@/assets/movies/movie17.jpg";
import movie18 from "@/assets/movies/movie18.jpg";
import movie19 from "@/assets/movies/movie19.jpg";
import movie20 from "@/assets/movies/movie20.jpg";
import movie21 from "@/assets/movies/movie21.jpg";
import movie22 from "@/assets/movies/movie22.jpg";
import movie23 from "@/assets/movies/movie23.jpg";
import movie24 from "@/assets/movies/movie24.jpg";
import movie25 from "@/assets/movies/movie25.jpg";
import movie26 from "@/assets/movies/movie26.jpg";
import movie27 from "@/assets/movies/movie27.jpg";
import movie28 from "@/assets/movies/movie28.jpg";
import movie29 from "@/assets/movies/movie29.jpg";
import movie30 from "@/assets/movies/movie30.jpg";
import movie31 from "@/assets/movies/movie31.jpg";
import movie32 from "@/assets/movies/movie32.jpg";
import movie33 from "@/assets/movies/movie33.jpg";
import movie34 from "@/assets/movies/movie34.jpg";
import movie35 from "@/assets/movies/movie35.jpg";
import movie36 from "@/assets/movies/movie36.jpg";
import movie37 from "@/assets/movies/movie37.jpg";
import movie38 from "@/assets/movies/movie38.jpg";
import movie39 from "@/assets/movies/movie39.jpg";
import movie40 from "@/assets/movies/movie40.jpg";
import movie41 from "@/assets/movies/movie41.jpg";
import movie42 from "@/assets/movies/movie42.jpg";
import movie43 from "@/assets/movies/movie43.jpg";
import movie44 from "@/assets/movies/movie44.jpg";


export default function Movies() {
  const movieData = [
    {
      title: "the penthouse",
      img: movie1,
      year: 2020,
    },
    {
      title: "long time no sex",
      img: movie2,
      year: 2020,
    },
    {
      title: "a shop for killer",
      img: movie3,
      year: 2020,
    },
    {
      title: "marry my husband",
      img: movie4,
      year: 2020,
    },
    {
      title: "taxi driver",
      img: movie5,
      year: 2020,
    },
    {
      title: "knight flower",
      img: movie6,
      year: 2020,
    },
    {
      title: "sweet home",
      img: movie7,
      year: 2020,
    },
    {
      title: "gyeongseong creature",
      img: movie8,
      year: 2020,
    },
    {
      title: "the worst of evil",
      img: movie9,
      year: 2020,
    },
    {
      title: "vincenzo",
      img: movie10,
      year: 2020,
    },
    {
      title: "killing vote",
      img: movie11,
      year: 2020,
    },
    {
      title: "moving",
      img: movie12,
      year: 2020,
    },
    {
      title: "revenant",
      img: movie13,
      year: 2020,
    },
    {
      title: "lies hidden in my garden",
      img: movie14,
      year: 2020,
    },
    {
      title: "the glory",
      img: movie15,
      year: 2020,
    },
    {
      title: "connect",
      img: movie16,
      year: 2020,
    },
    {
      title: "hospital playlist",
      img: movie17,
      year: 2020,
    },
    {
      title: "the queen umbrella",
      img: movie18,
      year: 2020,
    },
    {
      title: "one dollar lawyer",
      img: movie19,
      year: 2020,
    },
    {
      title: "my name",
      img: movie20,
      year: 2020,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />
      <NewsFeed />

      <main className="w-full bg-[#0a1016]">
        <div className="mx-auto max-w-4xl">
          <div className="grid-container grid  w-full grid-cols-1 gap-3 md:grid-cols-12 xl:gap-4 px-3 pb-12 pt-0 md:pb-16 md:pt-6 lg:px-0">
            <FilterMovie />

            <div className="col-start-1 md:col-span-12 md:col-start-0 md:row-start-2 xl:col-start-4">
              <section className="grid w-full grid-cols-2 gap-2 md:grid-cols-4 md:gap-2 xl:grid-cols-4 xl:gap-4">
                {movieData.map((data, index) => (
                  <div
                    className="transition-all duration-150 flex mr-[1em] mb-[1em] hover:scale-110"
                    key={index}
                  >
                    <div className="flex w-[200px] ">
                      <div className="rounded bg-transparent border border-gray-800 hover:border-[#00dc89] group flex flex-col overflow-hidden  transition duration-500 ease-in-out">
                        <Link href="/movies/angora" className="relative">
                          <Image
                            src={data.img}
                            alt=""
                            className="w-[300px] object-cover"
                          />{" "}
                          <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                        </Link>{" "}
                        <div className="px-3 py-2 flex flex-col justify-between leading-tight">
                        <div className="w-[197px]">
                          <h3 className="my-[0.25em] mx-[0em] md:text-md text-white leading-tight md:leading-tight font-semibold capitalize max-w-[85%] lg:max-w-[85%] line-clamp-1">
                            <Link href="/movies/one">{data.title}</Link>
                          </h3>{" "}
                        </div>
                          <div className="font-mabry text-xs text-white">
                            {data.year}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </section>
            </div>
          </div>
          <PaginateMovie />
        </div>
        
      </main>

      <SubscribeForm />
      <Footer />
    </>
  );
}
