import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";
import SubscribeForm from "../components/SubscribeForm";
import NewsReel from "../components/NewsReel";
import PaginateMovie from "../components/PaginateMovie";

import cast1 from "@/assets/actress/cast1.png";
import cast2 from "@/assets/actress/cast2.png";
import cast3 from "@/assets/actress/cast3.png";
import cast4 from "@/assets/actress/cast4.png";
import cast5 from "@/assets/actress/cast5.png";
import cast6 from "@/assets/actress/cast6.png";
import cast7 from "@/assets/actress/cast7.png";
import cast8 from "@/assets/actress/cast8.png";
import cast9 from "@/assets/actress/cast9.png";
import cast10 from "@/assets/actress/cast10.png";
import cast11 from "@/assets/actress/cast11.png";
import cast12 from "@/assets/actress/cast12.png";
import cast13 from "@/assets/actress/cast13.png";
import cast14 from "@/assets/actress/cast14.png";
import cast15 from "@/assets/actress/cast15.png";
import cast16 from "@/assets/actress/cast16.png";
import cast17 from "@/assets/actress/cast17.png";
import FilterPerson from "../components/FilterPerson";
import AvaArtist from "../components/AvaArtist";

export default function Person() {
  const actressData = [
    {
      name: "jang hyuk jin",
      img: cast1,
    },
    {
      name: "kim ji won",
      img: cast2,
    },
    {
      name: "esom",
      img: cast3,
    },
    {
      name: "kim eui sung",
      img: cast4,
    },
    {
      name: "yoo seung mok",
      img: cast5,
    },
    {
      name: "yoon eun hye",
      img: cast6,
    },
    {
      name: "seo jeong yeon",
      img: cast7,
    },
    {
      name: "lee ho chul",
      img: cast8,
    },
    {
      name: "gong yoo",
      img: cast9,
    },
    {
      name: "park shin hye",
      img: cast10,
    },
    {
      name: "lee yo joon",
      img: cast11,
    },
    {
      name: "park gyu young",
      img: cast12,
    },
    {
      name: "lee je hoon",
      img: cast13,
    },
    {
      name: "pyo ye jin",
      img: cast14,
    },
    {
      name: "bae suzy",
      img: cast15,
    },
    {
      name: "bae yoo ram",
      img: cast16,
    },
    {
      name: "yeonwoo",
      img: cast17,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />
      <NewsReel />

      <main className="w-full bg-[#0a1016]">
        <div className="mx-auto max-w-4xl">
          <div className="grid-container grid  w-full grid-cols-1 gap-3 md:grid-cols-12 xl:gap-4 px-3 pb-12 pt-0 md:pb-16 md:pt-6 lg:px-0">
            <FilterPerson />

            <div className="col-start-1 md:col-span-12 md:col-start-0 md:row-start-2 xl:col-start-4">
              <section className="grid w-full grid-cols-2 md:grid-cols-5 gap-2 md:gap-4 xl:grid-cols-4 xl:gap-4">
                {actressData.map((data, index) => (
                  <div
                    className="transition-all duration-150 flex mr-[1em] mb-[1em] hover:scale-110"
                    key={index}
                  >
                    <div className="flex w-[90px] md:w-[140px] ">
                      <div className="rounded bg-transparent  group flex flex-col overflow-hidden  transition duration-500 ease-in-out">
                        <Link href="/person/kim-ji-won" className="relative">
                          <Image
                            src={data.img}
                            alt=""
                            className="w-[138px] object-cover rounded-full border-2 border-[#0c9bff]"
                          />{" "}
                          <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                        </Link>{" "}
                        <div className="px-3 py-2 flex flex-col justify-center text-center leading-tight">
                          <h3 className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-md text-white leading-tight md:leading-tight font-semibold capitalize">
                            <Link href="/person/kim-ji-won">{data.name}</Link>
                          </h3>{" "}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
                <div className="transition-all duration-150 flex mr-[1em] mb-[1em] hover:scale-110">
                  <div className="flex w-[90px] md:w-[140px]">
                    <div className=" flex flex-col transition duration-500 ease-in-out">
                      <Link href="/person/kim-ji-won" className="flex w-[90px] h-[90px] md:w-[140px] md:h-[140px]">
                        <AvaArtist username={"Malcolm Goodwin"} />
                      </Link>
                      <div className="px-3 py-2 flex flex-col justify-center text-center leading-tight">
                        <h3 className="my-[0.25em] mx-[0em] overflow-hidden break-words text-sm md:text-md text-white leading-tight md:leading-tight font-semibold capitalize">
                          <Link href="/person/kim-ji-won">Malcolm Goodwin</Link>
                        </h3>{" "}
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </div>
          <PaginateMovie />
        </div>
      </main>

      <SubscribeForm />
      <Footer />
    </>
  );
}
